CREATE TABLE LANGUAGE (
  id    SERIAL PRIMARY KEY,
  name varchar(255) NOT NULL
);

CREATE TABLE MOVIE_LANG_MAPPING (
  MOVIE_ID INTEGER REFERENCES movie (id),
  LANG_ID INTEGER REFERENCES LANGUAGE (id)
);