CREATE TABLE LOCATION (
  id    SERIAL PRIMARY KEY,
  name varchar(255) NOT NULL
);

CREATE TABLE MOVIE_LOCATION_MAPPING (
  movie_id INTEGER REFERENCES MOVIE (id),
  lang_id INTEGER REFERENCES LANGUAGE (id)
);